name: Daily Brewery Data Pipeline

# ตั้งเวลาให้ทำงาน
on:
  schedule:
    # รันอัตโนมัติทุกๆ 8 โมงเช้าของเวลาไทย (01:00 UTC)
    - cron: '0 1 * * *' 
  workflow_dispatch: # ปุ่มกดสั่งรันauto

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest # เป้นการยืมคอมพิวเตอร์จำลองของ GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas boto3 requests fsspec s3fs pyarrow

      - name: Run Pipeline Scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          python getAPI.py
          python jsontocsv.py
          python load_to_cloud.py