name: Daily Brewery Data Pipeline

# ตั้งเวลาให้ทำงาน
on:
  schedule:
    # รันอัตโนมัติทุกๆ 8 โมงเช้าของเวลาไทย (01:00 UTC)
    - cron: '0 1 * * *' 
  workflow_dispatch: # ปุ่มกดสั่งรันauto

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest # เป้นการยืมคอมพิวเตอร์จำลองของ GitHub

    steps:
      # 1. โหลดไฟล์โค้ดทั้งหมดของเรามาไว้ในคอมจำลอง
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. install (Pandas, Boto3, ฯลฯ)
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4. สั่งรันโค้ด Python 
      - name: Run Pipeline Scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          python load_to_cloud.py